### PR TITLE
Maven Setup and Main class + Test of Main class added

### LINKED ISSUE #3: As a developer I want to set up a maven project so that I can manage dependencies and to automate bulid steps.

### PR DESCRIPTION
**Pull request by wi20b061**

### CODE REVIEW

**Comment by lukasfoidl** [comment]
looks fine to me

**Comment by lukasfoidl** [comment]
!! merge into main is not wanted here !!

**Comment by lukasfoidl** [comment]
thanks for changing branch ;)

**Review by NilsPetsch1999 — APPROVED** [review]
Nice one!

**Review by lukasfoidl — APPROVED** [review]

**Pull request merged**
